pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        // Checkout your Git repository
        git 'https://github.com/spoonart1/router.git'
      }
    }

    stage('Retrieve Pull Request Data') {
       steps {
          script {
            def utils = load './PullRequestUtils.groovy'
            def payload = readJSON file: env.CHANGE_PAYLOAD
            def data = utils.getPullRequestData(payload)

            // Print the retrieved data
            println "Pull Request ID: ${data.id}"
            println "Pull Request Title: ${data.title}"
            println "Pull Request Author: ${data.author}"
          }
       }
    }

    stage('Unit Tests') {
      steps {
        // Run your Android unit tests using Gradle
        //sh './gradlew test'
        println 'running unit test'
      }
    }

    stage('Build APK') {
      steps {
        // Build your Android APK using Gradle
        //sh './gradlew assembleDebug'
        println 'asmbling debug apk ...'
      }
    }

//     stage('Lint') {
//       steps {
//         // Run Android Lint for static code analysis
//         sh './gradlew lint'
//       }
//     }

    stage('Publish to Play Store') {
      steps {
      println 'publishing apk'
        // Publish your APK to the Play Store
//         withCredentials([string(credentialsId: 'your-google-play-credentials-id', variable: 'GOOGLE_PLAY_JSON_KEY')]) {
//           sh './gradlew publishApk -PgooglePlayJsonKey="$GOOGLE_PLAY_JSON_KEY"'
//         }
      }
    }
  }
}
